---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-pod
  namespace: test
  labels:
    app: image
spec: 
  minReadySeconds: 5
  replicas: 2
  selector: 
    matchLabels:
      app: web-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: web-app
      labels:
        app: web-app
    spec: 
      containers:
        - name: web-cont
          image: venkeyboda/k8s-deploy:1.0
          resources:
            limits:
              cpu: 250m
              memory: 128M 
          ports:
            - containerPort: 80

  