---
apiVersion: v1
kind: Service
metadata:
  name: svc-pod
  namespace: test
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
    - name: web-port 
      port: 80
      targetPort: 80
      protocol: "TCP"
       