---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  minReadySeconds: 10
  ordinals:
    start: 1
  replicas: 2
  selector:
    matchLabels:
      app: db
  serviceName: mysql-svc
  volumeClaimTemplates:
    - metadata:
       name: db-vol
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "local-path"
        resources:
          requests:
             storage: 1Gi          
  template: 
    metadata:
      name: mysql
      labels:
        app: db
    spec:
      containers:
        - name: mysql
          image: mysql:9
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: venkat
            - name: MYSQL_DATABASE
              value: build
            - name: MYSQL_USER
              value: build
            - name: MYSQL_PASSWORD
              value: venkat
          volumeMounts:
            - name: db-vol
              mountPath: /var/lib/mysql
                  
  

