name: website-deploy
labels:
  app: image-build
replicas: 2
minReadySeconds: 10
template:
  name: web-app
containers:
  name: web-container
  image: venkeyboda/k8s-deploy
  tags: "1.0"
limits:
  memory: 128M
  cpu: 250m
ports:
  name: service-port
  containerPort: 80
  port: 80
  targetPort:: 80
service:
  name: deploy-service
spec:
  type: NodePort
  app: image-build
