---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  minReadySeconds: {{ .Values.minReadySeconds}}
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  template:
    metadata: 
      name: {{ .Values.template.name }}
      labels: 
        app: {{ .Values.labels.app }}
    spec:
      containers:
        - name: {{ .Values.containers.name }}
          image: {{ .Values.containers.image }}:{{ .Values.containers.tags }}
          resources: 
            limits:
              memory: {{ .Values.limits.memory }}
              cpu: {{ .Values.limits.cpu }}
          ports:
            - containerPort: {{ .Values.ports.containerPort }}
