---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  type: {{ .Values.spec.type }}
  selector:
    app: {{ .Values.spec.app }}
  ports:
    - name: {{ .Values.service.name }}
      port: {{ .Values.ports.port }}
      targetPort: {{ .Values.ports.targetPort }}