---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: healet-rs
  labels:
    app: healet
    version: v1 
spec:
  minReadySeconds: 10
  replicas: 2
  selector: 
    matchLabels: 
      app: healet
  template: 
    metadata: 
      labels:
        app: healet
        version: v1 
    spec: 
      containers:
        - name: healet
          image: venkeyboda/healet:latest
          resources:
            limits:
              cpu: 250m
              memory: 128M
          ports: 
            - name: healet-port
              containerPort: 80
          startupProbe:
            exec:
              command:
                - pwd
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            tcpSocket: 
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: healet-svc
  labels:
    app: healet
spec:
  type: LoadBalancer
  selector: 
    app: healet
  ports: 
    - port: 80
      targetPort: 80
      protocol: TCP 