---
name: healet-rs
labels:
  app: healet
  version: v1
spec:
  minReadySeconds: 10
  replicas: 2
service:
  type: NodePort
  name: heleat-svc
  selector:
    app: healet
serviceports:    
  - Port: 80
    targetPort: 80
containers:
  name: healet
  image: venkeyboda/healet
  tags: latest
resources:
  limits:
    cpu: 250m
    memory: 128M
ports:
  - name: healet-port
    containerPort: 80
    