---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels: {{ .Values.labels | toYaml | nindent 4 }}
spec:
  type: {{ .Values.service.name }}
  selector: {{ .Values.service.selector | toYaml | nindent 4 }}
  ports: {{ .Values.serviceports | toYaml | nindent 4 }}
  