---
apiVersion: v1
kind: Pod
metadata: 
  name: mysql-pod
spec:
  containers:
    - name: mysql-pod
      image: mysql:9.2
      resources:
        limits:
          cpu: 250m
          memory: 128M
      ports:
        - containerPort: 3306
      envFrom:
        - secretRef:
            name: db-secrets
