---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
spec:
  containers:
    - name: httpd-pod
      image: httpd:alpine
    - name: sidecar
      image: alpine  
      args:
        - sleep
        - 1d
  initContainers: 
    - name: test
      image: alpine
      args:
        - sleep
        - 20s
    - name: test1
      image: alpine
      args:
        - sleep
        - 10s    
  ephemeralContainers:
    - name: test3
      image: alpine
      args:
        - sleep
        - 15s   
