---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
spec: 
  containers:
    - name: postgres-pod
      image: postgres:17.2
      env:
        - name: POSTGRES_PASSWORD
          value: venkat@02
        - name: POSTGRES_USER
          value: venkat
        - name: POSTGRES_DB
          value: postdb  
           
      