---
apiVersion: v1
kind: Pod
metadata:
  name: sql-test
spec:
  containers:
    - name: sql-test
      image: mysql:9.2.0
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: venkat@02
        - name: MYSQL_DATABASE
          value: mydb
        - name: MYSQL_USER
          value: mysql_db
        - name: MYSQL_PASSWORD
          value: venkat@02
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "yes"
        - name: MYSQL_ONETIME_PASSWORD
          value: venkat@02    