---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-template
  labels:
    app: dev
  annotations: 
    kubernetes.io/change-cause: "deployed version 1"
spec:
  minReadySeconds: 5
  replicas: 4
  selector:
    matchLabels:
      app: webapp
      env: dev
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: web-app
      labels: 
        app: webapp
        env: dev
        version: v1
    spec:
      containers: 
        - name: webapp
          image: venkeyboda/k8s-deploy:1.0
          resources:
            requests:
              memory: 100M
              cpu: 10m  
            limits:
              memory: 128M
              cpu: 250m
          ports: 
            - name: web-app
              containerPort: 80
          startupProbe:
            exec:
              command: 
                - pwd
            initialDelaySeconds: 25
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              port: 80
              path: /  
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3   

---
apiVersion: v1 
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  selector: 
    app: webapp
    env: dev
  ports:
    - name: web-port
      port: 80
      targetPort: 80
      protocol: "TCP"  
    

        
     


