apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    app: nginx
    env: dev
spec:
  minReadySeconds: 10
  replicas: 3
  selector:
    matchLabels:
      app: nginx 
    matchExpressions:
      - key: app
        operator: In
        values: 
          - nginx
      - key: env
        operator: Exists 
      - key: project
        operator: DoesNotExist
  template:
    metadata:
      labels:
        app: nginx
        version: v1 
        env: dev
    spec: 
      containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              cpu: 250m
              memory: 128M
          ports: 
            - containerPort: 80    

